apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamcity-k8s-agent.fullname" . }}-sa
  labels:
    {{- include "teamcity-k8s-agent.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity-k8s-agent.fullname" . }}-sa-token
  annotations:
    kubernetes.io/service-account.name: {{ include "teamcity-k8s-agent.fullname" . }}-sa
  labels:
    {{- include "teamcity-k8s-agent.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token

