apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teamcity-k8s-agent.fullname" . }}-scripts
data:
  smoketest.py: |-
{{ .Files.Get "files/smoketest.py" | indent 4 }}

  add-project.py: |-
{{ .Files.Get "files/add-project.py" | indent 4 }}
