{{- range .Values.podTemplates }}
apiVersion: v1
kind: PodTemplate
metadata:
  name: {{ .name | quote }}
  labels:
    {{- include "teamcity-k8s-agent.labels" $ | nindent 4 }}
template:
{{ toYaml .template | nindent 2 }}
---
{{- end }}

