apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "teamcity-k8s-agent.fullname" . }}
  labels:
    {{- include "teamcity-k8s-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["podtemplates"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "teamcity-k8s-agent.fullname" . }}
  labels:
    {{- include "teamcity-k8s-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "teamcity-k8s-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teamcity-k8s-agent.fullname" . }}-sa

