{{- if empty (include "teamcity-k8s-agent.name.apiToken" .) }}
{{- fail "apiToken secret is missing" }}
{{- end }}
{{- if and .Values.teamcity.apiToken (not .Values.teamcity.existingApiTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity-k8s-agent.fullname" . }}-token
  labels:
    {{- include "teamcity-k8s-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.teamcity.apiToken | b64enc | quote }}
{{- end }}


