{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity.fullname" . }}-shared-data
spec:
  accessModes:
    - {{ .Values.persistence.dataDir.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataDir.size | quote }}
  storageClassName: {{ coalesce .Values.persistence.dataDir.storageClass .Values.storageClass }}
{{- end }}

