{{- if empty (include "teamcity.name.databaseSecret" .) }}
{{- fail "database secret is missing" }}
{{- end }}
{{- if and .Values.teamcityGlobalConfigurations.database.url (not .Values.teamcityGlobalConfigurations.database.existingDatabaseSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-db
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.teamcityGlobalConfigurations.database.url | b64enc | quote }}
  username: {{ .Values.teamcityGlobalConfigurations.database.user | b64enc | quote }}
  password: {{ .Values.teamcityGlobalConfigurations.database.password | b64enc | quote }}
{{- end }}

