apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.name.serviceNameHeadless" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}

