teamcity:
  serverUrl: "http://ci-teamcity-main.teamcity-cluster.svc.cluster.local:8111"
  # Pass API token to automate agent registration
  # apiToken:
  # Or use existing secret
  # existingApiTokenSecret
  projects: []
  #  - id: "projectA"
  #    name: "Project A"
  #    k8sProfile:
  #      name: "K8s Profile A"
  #      apiServerUrl: "https://kubernetes.default.svc"
  #      namespace: "teamcity-agents"
  #      # following templateName from podTemplates[].name
  #      templateName: "my-template-1"
  #      # Maximum number of builds
  #      buildsLimit: 2
  #      # Parameters available in executor
  #      containerParameters:
  #        params1: value1
  #        params2: value2
  #    smokeTest:
  #      gitUrl: ""
  #      command: "pytest -v"
podTemplates:
  - name: my-template-1
    template:
      spec:
        containers:
          - name: template-container
            image: jetbrains/teamcity-agent
            resources:
              limits:
                ephemeral-storage: 25Gi
                memory: 2Gi
              requests:
                ephemeral-storage: 25Gi

rbac:
  roleName: teamcity-executor
  subjectKind: ServiceAccount
  subjectName: teamcity-k8s-sa
  subjectNamespace: "teamcity-agents"
