apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels.main" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "teamcity.selectorLabelsMain" . | nindent 6 }}

